#!/bin/sh
#callstack
# main routine for shelib functions
callstack(){
  #parseopts: parse options
  #parsecmds: parse subcommands
  #parseargs: parse other arguments
  #execute: execute stack set
  for i in parseopts parsecmds parseargs execute; do
    silent type $i && $i $@
  done
  #execute stack set with set_exec and no execute()
  silent type execute || ${exec_cmd:=throw exec_cmd not set};
  exit 0;
}
