#!/bin/sh
# check external executables to resolve dependency
require(){
  chk -e $1
  for shelib_i in $@; do
    shelib_setdir_loaded=${SHELIB_DIR:?SHELIB_DIR not defined}/${shelib_i##@}
    case $1 in
      @*/*) ## @shpkg/shmod syntax: load shelib module from SHELIB_DIR
        test -f ${shelib_setdir_loaded} || throw "$1 not exist in shelibdir"
        . $shelib_setdir_loaded || throw "loading failure" ;;
      @*) ## @shpkg syntax: load all shelib module from shpkg
        test -d "$shelib_setdir_loaded" \
          && for shelib_j in $shelib_setdir_loaded/* ; do test -f $shelib_j && . $shelib_j ; done \
          || throw shpkg $1 not found;;
      /*) ## /path/to/script syntax: directly load script with full path
        test -f $1 && . $1 || throw "failed to load $1" ;;
      *) ## generic requirement check: check executable exists in PATH or not
        sanitize $shelib_i; chk -x $shelib_i ;;
    esac
  done
  return 0
}
