#!/bin/sh
# rearrange document from stream to add/delete tab
tabfix(){
  sed -r \
    -e s/\^\ \+/\ \ /g \
    -e s/\#\#/\\\t/g \
    -e "s/^[^\(]+\)/&SHELIB_CHARDEL/g" \
    -e "s/\)SHELIB_CHARDEL//g" \
    -e "s/\#[[:punct:][:alnum:]]+/SHELIB_CHARDEL&SHELIB_CHARDEL/g" \
    -e "s/SHELIB_CHARDEL\#?//g" \
    -e "s/SHELIB_CHARDEL *\t*//g" \
    -e "s/\|[[:alnum:]]+//g" \
    -e "s/\tBREAK_OPT//g" \
    -e "s/\ BREAK_OPT//g" \
    -e "s/\t{4}/\t\t\t/g" \
    -e "s/\t{4}/\t\t\t/g" \
    -e "s/\t{4}/\t\t\t/g" \
    -e "s/^[^\t]{3,8}\t/&SHELIB_TABADD/g" \
    -e "s/\tSHELIB_TABADD/\t\t/g" \
    -e "s/^[^\t]{8,15}\t/&SHELIB_TABADD/g" \
    -e "s/\tSHELIB_TABADD/\t\t/g" \
    -e "s/^[^\t]{24}( |[[:graph:][:punct:]])*\t{2}/&SHELIB_TABDEL/g" \
    -e "s/\tSHELIB_TABDEL//g" \
    -e "s/^[^\t]{24}( |[[:graph:][:punct:]])*\t{2}/&SHELIB_TABDEL/g" \
    -e "s/\tSHELIB_TABDEL//g" \
    -e "s/^[^\t]{16,23}\t{2}/&SHELIB_TABDEL/g" \
    -e "s/\tSHELIB_TABDEL//g" \
    -e "s/^[^\t]{16,23}\t{2}/&SHELIB_TABDEL/g" \
    -e "s/\tSHELIB_TABDEL//g" \
    -e "s/^[^\t]{16,23}\t{2}/&SHELIB_TABDEL/g" \
    -e "s/\tSHELIB_TABDEL//g" \
    -e "s/^[^\t]{8,15}*\t{3}/&SHELIB_TABDEL/g" \
    -e "s/\tSHELIB_TABDEL//g" \
    -e "s/^[^\t]{8,15}*\t{3}/&SHELIB_TABDEL/g" \
    -e "s/\tSHELIB_TABDEL//g" 
}
