#!/bin/sh
# dum2: dummy shelib function for showhelp UT

dum2(){
version=0.1.0

loadenv(){
  DUMENV="dumdum"
}

#SHELIB_OPTIONS
parseopts(){
  case $1 in
    -t|--type) #type
    ##set dummy type
    : ;;

    -F|--fix) ##MISC
    ##fix dummy
    : ;;

    -d|--date) #day|+N|-N
    ##dummy date
    : ;;

    -l*|--list) ##BREAK_OPT
    ##list dummy
    : ;;

    -D|--directory) #dir
    ##specify dummy dir
    : ;;

    -h|--help) #[--short] ##BREAK_OPT
    ##show this help
    setexec "showhelp $2"; return 0 ;;

    -v|--version) ##BREAK_OPT
    ##show version
    : ;;

    *)
    : ;;
  esac

}
#SHELIB_OPTIONS

}

cook dum2 $@
